sudo: required
services:
  - docker

language: generic

before_script:
  - mkdir -p ~/docker
  - |
      ls ~/docker
      if [[ -f ~/docker/flatpak.tgz ]]; then
        (set -x; zcat ~/docker/flatpak.tgz | docker load)
      else
        (set -x;
         docker pull flatpak/flatpak-builder:gnome-3-28;
         docker save flatpak/flatpak-builder:gnome-3-28 | gzip -c > ~/docker/flatpak.tgz)
      fi

script:
  - env | grep 'TRAVIS\|encrypted' > travis.env
  - >
      docker run --env-file travis.env -it --rm
      --mount type=bind,source=$PWD/travis/run.sh,target=/run.sh
      flatpak/flatpak-builder:gnome-3-28 /run.sh

cache:
  directories:
    - ~/docker
