sudo: required
services:
  - docker

language: generic

before_script:
  - mkdir -p ~/docker
  - docker pull flatpak/flatpak-builder:gnome-3-28

script:
  - env | grep 'TRAVIS\|encrypted' > travis.env
  - >
      docker run --privileged --env-file travis.env -it --rm
      --mount type=bind,source=$PWD,target=/workspace
      flatpak/flatpak-builder:gnome-3-28 /workspace/travis/run.sh
